# Generated by Django 3.2 on 2021-04-11 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=150)),
                ('code_matricule', models.CharField(max_length=10)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'chauffeur',
                'verbose_name_plural': 'chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('categorie', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('DGE', 'Dir. Générale(DGE)'), ('DCF', 'Dir. Financière(DCF)'), ('DRH', 'Dir. RH(DRH)'), ('DEX', 'Dir. Exploitation(DEX)'), ('DET', 'Dir. Technique(DET)'), ('DCM', 'Dir. Commerciale(DCM)'), ('SMG', 'Moyens Generaux(SMG)'), ('FHY', 'fret Hydrocarbure(FHY)'), ('FSB', 'fret boisson(FSB)'), ('FHP', 'fret huile de palm(FHP)'), ('FTC', 'fret conteneurs(FTC)'), ('FCS', 'fret canne à sucre(FCS)'), ('FDI', 'fret divers(FDI)'), ('LEV', 'levage(LEV)'), ('LOC', 'location de surfaces(LOC)'), ('SDI', 'services divers(SDI)'), ('RAV', 'revenus à ventiler(RAV)'), ('PAF', 'Prestation Accessoir(PAF)'), ('COL', 'fret Colis lourds(COL)')], max_length=50)),
                ('code_matricule', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soumis', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('demande_date', models.DateTimeField(auto_now_add=True)),
                ('soumis', models.BooleanField(default=False)),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('num_releve', models.CharField(max_length=20, verbose_name='Numéro de relevé')),
                ('code_vehicule', models.CharField(max_length=50, null=True, verbose_name='Code véhicule')),
                ('code_remorque', models.CharField(max_length=50, verbose_name='Code remorque')),
                ('imat_vehicule', models.CharField(max_length=50, verbose_name='Imat. véhicule')),
                ('imat_remorque', models.CharField(max_length=50, verbose_name='Imat. Remorque')),
                ('frais_date', models.DateField(verbose_name='Date de frais')),
                ('code_activite', models.CharField(choices=[('DGE', 'DGE'), ('DCF', 'DCF'), ('DRH', 'DRH'), ('DEX', 'DEX'), ('DET', 'DET'), ('DCM', 'DCM'), ('SMG', 'SMG'), ('FHY', 'FHY'), ('FSB', 'FSB'), ('FHP', 'FHP'), ('FTC', 'FTC'), ('FCS', 'FCS'), ('FDI', 'FDI'), ('LEV', 'LEV'), ('LOC', 'LOC'), ('SDI', 'SDI'), ('RAV', 'RAV'), ('PAF', 'PAF'), ('COL', 'COL')], max_length=150, verbose_name='Code Activité')),
                ('libelle_activite', models.CharField(choices=[('DGE', 'Dir. Générale(DGE)'), ('DCF', 'Dir. Financière(DCF)'), ('DRH', 'Dir. RH(DRH)'), ('DEX', 'Dir. Exploitation(DEX)'), ('DET', 'Dir. Technique(DET)'), ('DCM', 'Dir. Commerciale(DCM)'), ('SMG', 'Moyens Generaux(SMG)'), ('FHY', 'fret Hydrocarbure(FHY)'), ('FSB', 'fret boisson(FSB)'), ('FHP', 'fret huile de palm(FHP)'), ('FTC', 'fret conteneurs(FTC)'), ('FCS', 'fret canne à sucre(FCS)'), ('FDI', 'fret divers(FDI)'), ('LEV', 'levage(LEV)'), ('LOC', 'location de surfaces(LOC)'), ('SDI', 'services divers(SDI)'), ('RAV', 'revenus à ventiler(RAV)'), ('PAF', 'Prestation Accessoir(PAF)'), ('COL', 'fret Colis lourds(COL)')], max_length=255, verbose_name='Libelle')),
                ('agence', models.CharField(choices=[('0000', 'Siège'), ('0001', 'Abidjan (agence principale)'), ('0002', 'Bouaflé'), ('0003', 'San-Pedro'), ('0007', 'Bouaké'), ('0008', 'Yamoussoukro'), ('0009', 'Ferké'), ('0010', 'Minautores')], max_length=255)),
                ('a_rembourser', models.BooleanField(default=False)),
                ('axe_analyse', models.CharField(choices=[('200', 'Batiment et charge locative'), ('210', 'Voyage & deplacement'), ('220', 'Fourniture & consommable de bureau'), ('230', 'Charge personnel'), ('240', 'Quote-part depreciation immo'), ('250', 'Personnel & services exterieur'), ('260', 'Relation exterieur'), ('270', 'Impôt & taxes'), ('280', 'Autres charges directions et service'), ('900', "Recette d'exploitation"), ('910', 'Frais/Opération (frais voyages)'), ('920', 'Papier administratif-CR'), ('930', "Main d'oevre dédiée"), ('940', 'Quote-part amortissement CR et autres'), ('950', 'Entretien & reparation CR'), ('960', 'Frais generaux')], max_length=255)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur', to='core.chauffeur')),
                ('items', models.ManyToManyField(to='core.DemandeItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-demande_date', 'libelle_activite'),
            },
        ),
    ]
