# Generated by Django 3.2 on 2021-04-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_demande_frais_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
