# Generated by Django 3.2 on 2021-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demande_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='montant_ttc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
