# Generated by Django 3.2 on 2021-04-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_demande_montant_ttc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='demande_date',
            field=models.DateTimeField(null=True, verbose_name='Date de demande'),
        ),
    ]
