# Generated by Django 3.2 on 2021-04-15 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_demande_demande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='code_matricule',
            field=models.CharField(max_length=10, verbose_name='Code matricule'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Est Actif'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='nom_prenom',
            field=models.CharField(max_length=150, verbose_name='Nom et prénoms'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='a_rembourser',
            field=models.BooleanField(default=False, verbose_name='A rembourser'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='items',
            field=models.ManyToManyField(to='core.DemandeItem', verbose_name='Motifs'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='libelle_activite',
            field=models.CharField(choices=[('DGE', 'Dir. Générale(DGE)'), ('DCF', 'Dir. Financière(DCF)'), ('DRH', 'Dir. RH(DRH)'), ('DEX', 'Dir. Exploitation(DEX)'), ('DET', 'Dir. Technique(DET)'), ('DCM', 'Dir. Commerciale(DCM)'), ('SMG', 'Moyens Generaux(SMG)'), ('FHY', 'fret Hydrocarbure(FHY)'), ('FSB', 'fret boisson(FSB)'), ('FHP', 'fret huile de palm(FHP)'), ('FTC', 'fret conteneurs(FTC)'), ('FCS', 'fret canne à sucre(FCS)'), ('FDI', 'fret divers(FDI)'), ('LEV', 'levage(LEV)'), ('LOC', 'location de surfaces(LOC)'), ('SDI', 'services divers(SDI)'), ('RAV', 'revenus à ventiler(RAV)'), ('PAF', 'Prestation Accessoir(PAF)'), ('COL', 'fret Colis lourds(COL)')], max_length=255, verbose_name='Libelle activité'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='montant_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demande',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code unique'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilistaeur'),
        ),
        migrations.AlterField(
            model_name='item',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=9999),
        ),
    ]
