# Generated by Django 3.2 on 2021-04-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_demande_montant_ttc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='code_remorque',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code remorque'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='code_vehicule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code véhicule'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='imat_remorque',
            field=models.CharField(blank=True, max_length=50, verbose_name='Imat. Remorque'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='imat_vehicule',
            field=models.CharField(blank=True, max_length=50, verbose_name='Imat. véhicule'),
        ),
    ]
