# Generated by Django 3.2 on 2021-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210416_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='code_vehicule',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code véhicule'),
        ),
    ]
